version: '2.1'
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn install
          name: Install deps
      - run:
          command: yarn test
          name: Run YARN tests
workflows:
  test_my_app:
    jobs:
      - test
